# Generated by Django 5.2.3 on 2025-07-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="yookassa_payment_id",
            field=models.CharField(
                help_text="Используется для идемпотентности вебхуков.",
                max_length=255,
                unique=True,
                verbose_name="ID платежа в ЮKassa",
            ),
        ),
    ]
