# Список репозиториев, из которых мы будем брать хуки
repos:
  # Стандартные хуки для поддержания чистоты файлов
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace # Удаляет лишние пробелы в конце строк
      - id: end-of-file-fixer  # Гарантирует, что файл заканчивается одной пустой строкой
      - id: check-yaml           # Проверяет синтаксис YAML файлов
      - id: check-added-large-files # Предотвращает коммит больших файлов

  # Хук для линтинга и форматирования с помощью Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        args: [ --fix ] # Автоматически исправлять найденные проблемы
      - id: ruff-format

  # Наш локальный хук для проверки уязвимостей
  - repo: local
    hooks:
      - id: pip-audit
        name: pip-audit
        # Добавляем флаг для игнорирования конкретной уязвимости в ecdsa
        entry: poetry run pip freeze > requirements.txt && poetry run pip-audit -r requirements.txt --ignore-vuln GHSA-wj6h-64fc-37mp
        language: system
        pass_filenames: false
        always_run: true
