services:
  # Сервис нашего Django-приложения
  app:
    build:
      context: .
      target: app # Используем финальную стадию 'app'
    container_name: psyai_app
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      # Пробрасываем код для live-reloading
      - .:/app
      # А для медиафайлов используем именованный том, который сохранит права
      - media_volume:/app/media
    ports:
      - "9000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped

  # Сервис базы данных PostgreSQL
  db:
    image: postgres:15
    container_name: psyai_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: psyai_user
      POSTGRES_PASSWORD: psyai_password
      POSTGRES_DB: psyai_db
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Сервис брокера сообщений Redis
  redis:
    image: redis:7-alpine
    container_name: psyai_redis
    restart: unless-stopped

  # Сервис для фоновых задач Celery
  worker:
    build:
      context: .
      target: app # Используем ту же стадию, что и для 'app'
    container_name: psyai_worker
    command: celery -A config worker -l info
    volumes:
      # Код нужен и воркеру
      - .:/app
      # Медиафайлы могут понадобиться и воркеру (например, для обработки)
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    user: appuser

  # Мониторинг Celery через Flower
  flower:
    build:
      context: .
      target: flower # Используем специальную, минимальную стадию 'flower'
    container_name: psyai_flower
    command: celery -A config flower
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "5555:5555"
    depends_on:
      - redis
    restart: unless-stopped
    user: appuser

# Определяем наши именованные тома здесь
volumes:
  postgres_data:
  media_volume:
