"""
Django settings for psyai-chat project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

import environ

# --- 1. Настройка Environ ---
# Определяем базовую директорию проекта (корень, где лежит manage.py)
# BASE_DIR -> psyai-chat/
BASE_DIR = Path(__file__).resolve().parent.parent

# Инициализируем environ
env = environ.Env(
    # Устанавливаем значения по умолчанию и тип для DEBUG
    DJANGO_DEBUG=(bool, False)
)

# Ищем и читаем переменные из файла .env в корне проекта
env_path = BASE_DIR / ".env"
if os.path.exists(env_path):
    environ.Env.read_env(env_path)


# --- 2. Ключевые настройки безопасности ---
# Секретный ключ берется из .env файла. Никогда не храните его в коде!
SECRET_KEY = env("DJANGO_SECRET_KEY")

# Режим отладки берется из .env файла.
DEBUG = env("DJANGO_DEBUG")

# Список хостов, которые могут обслуживать этот сайт.
# В режиме DEBUG можно оставить пустым, но для Docker лучше указать.
ALLOWED_HOSTS = []


# --- 3. Приложения ---
INSTALLED_APPS = [
    "core.apps.CoreConfig",
    "users.apps.UsersConfig",
    "chat.apps.ChatConfig",
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # Указываем общую папку для шаблонов
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# --- 4. База данных ---
# Конфигурация БД полностью берется из переменной DATABASE_URL.
# Это позволяет легко переключаться между SQLite, PostgreSQL и т.д.
DATABASES = {"default": env.db("DATABASE_URL")}


# --- 5. Валидаторы паролей ---
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# --- 6. Интернационализация ---
LANGUAGE_CODE = "ru-ru"
TIME_ZONE = "Europe/Moscow"
USE_I18N = True
USE_TZ = True


# --- 7. Статические файлы (CSS, JavaScript, Images) ---
STATIC_URL = "static/"
# Директория, куда `collectstatic` будет собирать все статические файлы для продакшена.
STATIC_ROOT = BASE_DIR / "staticfiles"


# --- 8. Настройки по умолчанию для моделей ---
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --- 9. Кастомная модель пользователя ---
# Указываем Django использовать нашу модель User вместо стандартной.
AUTH_USER_MODEL = "users.User"

# --- 10. Настройки редиректов после входа/выхода ---
LOGIN_REDIRECT_URL = "profile"  # Имя маршрута для перенаправления после входа
LOGOUT_REDIRECT_URL = "home"  # Имя маршрута для перенаправления после выхода

# --- 11. Настройка ASGI и Channels ---
# Указываем Django, где находится наше основное ASGI-приложение.
# Это необходимо для работы Django Channels.
ASGI_APPLICATION = "config.asgi.application"