# Generated by Django 5.2.3 on 2025-06-24 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_image",
                    models.ImageField(
                        upload_to="image_analysis/%Y/%m/%d/",
                        verbose_name="Исходное изображение",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "В обработке"),
                            ("COMPLETED", "Завершено"),
                            ("FAILED", "Ошибка"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Статус анализа",
                    ),
                ),
                (
                    "result_payload",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Результат от API"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Сообщение об ошибке"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат анализа изображения",
                "verbose_name_plural": "Результаты анализов изображений",
                "ordering": ["-created_at"],
            },
        ),
    ]
